# Credenciales del proyecto
sonar.projectKey=LosTresMosquetones_diplo_gyc
sonar.organization=lostresmosquetones
sonar.projectName=diplo_gyc

# Carpetas donde está tu código fuente a analizar
sonar.sources=backend,frontend,bff

# Carpetas y archivos a ignorar
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.github/**,**/actions-runner/**

# Codificación estándar
sonar.sourceEncoding=UTF-8

# Le decimos dónde están los compilados (.class)
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,bff/coverage/lcov.info

sonar.coverage.exclusions=**/*Test.java,**/*.test.jsx,**/*.test.js
