on:
  push:
    branches:
      - 'feature_**'
      - 'hotfix_**'

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      bff: ${{ steps.filter.outputs.bff }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            bff:
              - 'bff/**'
            backend:
              - 'backend/**'
